include::includes/_adoc/common_options.adoc[]

= Infrastructure

== Document Objective

This document introduces the infrastructure of the project and the different platforms from dev to production.

== Continous Integration

=== Jenkins

Jenkins is used as for continuous integration. It's deployed on htpp://127.0.0.1/ server.

TIP: Jenkins use an AD authentification, ask the right IAM rights to launch projects.

=== Job configurations

Jobs are configured using pipelines and Jenkinsfiles.

The following jobs are today configured :

- *Merge request pipeline* : compile and run tests....
- *Master CI* : ...
- *Integration Tests* : ...
- *Release* : See release process documentation...
 
To modify a job, you have to...

=== SONAR

The Sonar Server is located at htpp://127.0.0.1/sonar.

TIP: Jenkins use an AD authentification, connect with your account to see issues.

== Run platforms

=== Development and tests environments

X environments are dedicated to development and ...

=== Integration environment

All important informations to connect to the environnement, to execute or retrieve informations.

Per hoc minui studium suum existimans Paulus, ut erat in conplicandis negotiis artifex dirus, unde ei Catenae inditum est cognomentum, vicarium ipsum eos quibus praeerat adhuc defensantem ad sortem periculorum communium traxit. et instabat ut eum quoque cum tribunis et aliis pluribus ad comitatum imperatoris vinctum perduceret: quo percitus ille exitio urgente abrupto ferro eundem adoritur Paulum. et quia languente dextera, letaliter ferire non potuit, iam districtum mucronem in proprium latus inpegit. hocque deformi genere mortis excessit e vita iustissimus rector ausus miserabiles casus levare multorum.

=== Production environment

Dumque ibi diu moratur commeatus opperiens, quorum translationem ex Aquitania verni imbres solito crebriores prohibebant auctique torrentes, Herculanus advenit protector domesticus, Hermogenis ex magistro equitum filius, apud Constantinopolim, ut supra rettulimus, populari quondam turbela discerpti. quo verissime referente quae Gallus egerat, damnis super praeteritis maerens et futurorum timore suspensus angorem animi quam diu potuit emendabat.