name: Build and deploy documentation
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install graphviz/dot command
      run: sudo apt-get install graphviz
      
    - name: Checkout sources
      uses: actions/checkout@v2
    
    # Build and install (running integration tests)
    - name: Build and verify
      run: mvn clean verify

    # Deploy to github pages
    - name: Deploy an example on a project github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/test-classes/projects/nominalTestCase/project/myProjectArtifactId/target/html5
